name: ci
on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.sum"
      - "**/go.mod"
      - ".golangci.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.sum"
      - "**/go.mod"
      - ".golangci.yml"

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Cache golangci-lint cache
        id: cache-golangci-lint
        env:
          cache-name: cache-golangci-lint
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.6
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        env:
          cache-name: cache-go-mod
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.cache-name }}-
            ${{ runner.os }}-go-
            ${{ runner.os }}-
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable
      - name: Run tests
        run: go test ./... -v -
